config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'tester_mode', to: 'application#set_tester_mode'
  devise_for :user, controllers: { registrations: 'users/registrations' }
  namespace :class_diagram do
    resources :diagramas
    resources :classes, except: [:index, :show]
  end
  namespace :use_case_diagram do
    resources :diagramas
    resources :elementos, except: [:index, :show]
  end
  namespace :state_machine_diagram do
    resources :diagramas
    resources :elementos, except: [:index, :show]
  end
  namespace :users do
    resource :resources, only: [:edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/associacao.rb
class Associacao < ApplicationRecord
  belongs_to :classe
  validates :classe_destino, presence: true
  validates :tipo_associacao, presence: true
  validates :multi_a, presence: true, if:-> { UMLAssociation? }
  validates :multi_b, presence: true, if:-> { UMLAssociation? }
  enum tipo_associacao: [:UMLAggregation, :UMLAssociation, :UMLComposition, :UMLDependency, :UMLGeneralization, :UMLRealization]
  def self.associacoes
    [
      ['Agregação', 'UMLAggregation'],
      ['Associação', 'UMLAssociation'],
      ['Composicação', 'UMLComposition'],
      ['Depedência', 'UMLDependency'],
      ['Generalização', 'UMLGeneralization'],
      ['Realização', 'UMLRealization']
    ]
  end
end

app/models/class_diagram/diagrama.rb
class ClassDiagram::Diagrama < ApplicationRecord
  belongs_to :user
  has_many :class_diagram_classe, class_name: 'ClassDiagram::Classe'
  validates :nome, presence: true
  before_validation :set_user
  before_destroy :remove_dependencias
  private
  def set_user
    self.user_id = Current.user.id
  end
  def remove_dependencias
    ClassDiagram::Classe.where(class_diagram_diagrama_id: id).delete_all
  end
end

app/models/classo.rb
class CLASSO < ApplicationRecord
  belongs_to :cldiag
  validates :clclas_origem_id,  presence: true
  validates :clclas_destino_id, presence: true
  validates :multi_origem,  presence: true, if:-> { UMLAssociation? }
  validates :multi_destino, presence: true, if:-> { UMLAssociation? }
  validates :tipo_associacao, presence: true
  enum tipo_associacao: [:UMLAggregation, :UMLAssociation, :UMLComposition, :UMLDependency, :UMLGeneralization, :UMLRealization]
  def self.associacoes
    [
      ['Agregação', 'UMLAggregation'],
      ['Associação', 'UMLAssociation'],
      ['Composicação', 'UMLComposition'],
      ['Depedência', 'UMLDependency'],
      ['Generalização', 'UMLGeneralization'],
      ['Realização', 'UMLRealization']
    ]
  end
end

app/models/clatri.rb
class CLATRI < ApplicationRecord
  belongs_to :clclas
  validates :descricao, presence: true
end

app/models/clclas.rb
class CLCLAS < ApplicationRecord
  belongs_to :cldiag
  has_many :clatri, :dependent => :destroy
  has_many :clmeto, :dependent => :destroy
  accepts_nested_attributes_for :clatri, allow_destroy: true
  accepts_nested_attributes_for :clmeto, allow_destroy: true
  validates_associated :clatri
  validates_associated :clmeto
  validates :nome, presence: true
  before_destroy :remove_dependencias
  private
    def remove_dependencias
      CLATRI.where(clclas_id: id).delete_all
      CLMETO.where(clclas_id: id).delete_all
      CLASSO.where(clclas_origem_id:  id).delete_all
      CLASSO.where(clclas_destino_id: id).delete_all
    end
end

app/models/cldiag.rb
class CLDIAG < ApplicationRecord
  belongs_to :user
  has_many :clclas
  has_many :classo, :dependent => :destroy
  accepts_nested_attributes_for :classo, allow_destroy: true
  validates_associated :classo
  validates :nome, presence: true
  before_validation :set_user
  before_destroy :remove_dependencias
  private
  def set_user
    self.user_id = Current.user.id
  end
  def remove_dependencias
    CLASSO.where(cldiag_id: id).delete_all
    CLCLAS.where(cldiag_id: id).each do |clclas|
      CLATRI.where(clclas_id: clclas.id).delete_all
      CLMETO.where(clclas_id: clclas.id).delete_all
      clclas.delete
    end
  end
end

app/models/clmeto.rb
class CLMETO < ApplicationRecord
  belongs_to :clclas
  validates :descricao, presence: true
end

app/models/concerns/current.rb
module Current
  thread_mattr_accessor :user
end

app/models/csasso.rb
class CSASSO < ApplicationRecord
  belongs_to :csdiag
  validates :cselem_origem_id,  presence: true
  validates :cselem_destino_id, presence: true
  validates :tipo_associacao, presence: true
  enum tipo_associacao: [:UMLCommunication, :UMLInclude, :UMLExtend, :UMLGeneralization]
  def self.associacoes
    [
      ['Associação', 'UMLCommunication'],
      ['Inclusão', 'UMLInclude'],
      ['Extensão', 'UMLExtend'],
      ['Generalização', 'UMLGeneralization']
    ]
  end
end

app/models/csdiag.rb
class CSDIAG < ApplicationRecord
  belongs_to :user
  has_many :cselem
  has_many :csasso, :dependent => :destroy
  accepts_nested_attributes_for :csasso, allow_destroy: true
  validates_associated :csasso
  validates :nome, presence: true
  before_validation :set_user
  before_destroy :remove_dependencias
  private
  def set_user
    self.user_id = Current.user.id
  end
  def remove_dependencias
    CSASSO.where(csdiag_id: id).delete_all
    CSELEM.where(csdiag_id: id).delete_all
  end
end

app/models/cselem.rb
class CSELEM < ApplicationRecord
  belongs_to :csdiag
  enum tipo_elemento: [:Actor, :UseCase]
  validates :descricao, presence: true
  validates :tipo_elemento, presence: true
  def self.tipo_elementos
    [ ['Ator', 'Actor'], ['Caso de Uso', 'UseCase'] ]
  end
  before_destroy :remove_dependencias
  private
    def remove_dependencias
    CSASSO.where(cselem_origem_id:  id).delete_all
    CSASSO.where(cselem_destino_id: id).delete_all
  end
end

app/models/mqdiag.rb
class MQDIAG < ApplicationRecord
  belongs_to :user
  has_many :mqelem
  has_many :mqtran, :dependent => :destroy
  accepts_nested_attributes_for :mqtran, allow_destroy: true
  validates_associated :mqtran
  validates :nome, presence: true
  before_validation :set_user
  before_destroy :remove_dependencias
  private
  def set_user
    self.user_id = Current.user.id
  end
  def remove_dependencias
    MQTRAN.where(mqdiag_id: id).delete_all
    MQELEM.where(mqdiag_id: id).delete_all
  end
end

app/models/mqelem.rb
class MQELEM < ApplicationRecord
  belongs_to :mqdiag
  validates :descricao, presence: true
  before_destroy :remove_dependencias
  private
  def remove_dependencias
    MQTRAN.where(mqelem_origem_id:  id).delete_all
    MQTRAN.where(mqelem_destino_id: id).delete_all
    mqdiag.update(mqelem_inicial_id: nil) if mqdiag.mqelem_inicial_id == id
    mqdiag.update(mqelem_final_id:   nil) if mqdiag.mqelem_final_id   == id
  end
end

app/models/mqtran.rb
class MQTRAN < ApplicationRecord
  belongs_to :mqdiag
  validates :mqelem_origem_id,  presence: true
  validates :mqelem_destino_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :class_diagram_diagrama
  devise :database_authenticatable, :registerable#, :validatable
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 3 }, if: :force_password?
  validates_confirmation_of :password
  def force_password?
    self.id.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:set_tester_mode], unless: :tester_mode?
  around_action :set_current_user

  $tester_mode = false

  def set_tester_mode
    $tester_mode = params[:tester_mode].to_bool
    redirect_to request.referer
  end

  def tester_mode?
    $tester_mode ? (@current_user = User.first) : (@current_user = current_user)
    return $tester_mode
  end

  def catch(resource)
    resource.errors.full_messages.join(". ") + "."
  end

  def after_sign_in_path_for(resource)
    root_path || stored_location_for(resource)
  end
  protected
  def set_current_user
    Current.user = current_user
    yield
  ensure
    # to address the thread variable leak issues in Puma/Thin webserver
    Current.user = nil
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @title = 'Ínicio'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def val_of(object, symbol)
    params[symbol] || object[symbol]
  end

  def options_from_enum_for_select(hash)
    hash.map { |i| [i[0].capitalize, i[0]] }
  end

  def date(value)
    if !value.nil?
      l value
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="description"content="Trabalho de Conclusão de Curso">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Plataforma Blindfolded Entrada</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="description"content="Trabalho de Conclusão de Curso">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'devise', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav id="menu">
  <ul>
    <li><%= link_to 'Home', root_path, accesskey: '1' %></li>
    <li><%= link_to 'Diagrama de Classes', class_diagram_diagramas_index_path, accesskey: '2' %></li>
    <li><%= link_to 'Diagrama de Caso de Uso', use_case_diagram_diagramas_index_path, accesskey: '3' %></li>
    <li><%= link_to 'Diagrama de Máquina de Estado', state_machine_diagram_diagramas_index_path, accesskey: '4' %></li>
    <li><%= link_to 'Perfil', edit_users_resources_path, accesskey: '5' %></li>
    <li><%= link_to 'Sair', destroy_user_session_path, method: :delete, accesskey: '6' %></li>
  </ul>
</nav>
<%= render 'layouts/shared/notification' %>
<hr class="divide">

app/views/layouts/shared/_notification.html.erb
<p class="notification"><%= flash[:error] || flash[:alert] || flash[:notice] || 'Nenhuma notificação.' %></p>