config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'tester_mode', to: 'application#set_tester_mode'
  devise_for :user, controllers: { registrations: 'users/registrations' }
  namespace :class_diagram do
    resources :diagramas
    resources :classes, except: [:index, :show]
  end
  namespace :use_case_diagram do
    resources :diagramas
    resources :elementos, except: [:index, :show]
  end
  namespace :state_machine_diagram do
    resources :diagramas
    resources :elementos, except: [:index, :show]
  end
  namespace :users do
    resource :resources, only: [:edit, :update]
  end
end

app/controllers/state_machine_diagram/elementos_controller.rb
class StateMachineDiagram::ElementosController < ApplicationController
  before_action :set_elemento, only: [:edit, :update, :destroy]
  before_action :set_diagrama, only: [:new, :edit]

  def new
    @elemento = MQELEM.new
    @title = 'Novo Elemento'
  end

  def edit
    @title = 'Editando Elemento'
  end

  def create
    respond_to do |format|
      begin
        @elemento = MQELEM.new(elemento_params)
        if @elemento.save
          flash[:notice] = 'Elemento criada com sucesso.'
          format.html { redirect_to edit_state_machine_diagram_elementos_path(@elemento, mqdiag_id: params[:mqelem][:mqdiag_id]) }
        end
        if @elemento.errors.any?
          flash[:alert] = catch(@elemento)
          @params_for_reload = elemento_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = elemento_params
      end
      format.html { redirect_to new_state_machine_diagram_elementos_path(params: @params_for_reload) }
    end
  end

  def update
    respond_to do |format|
      begin
        flash[:notice] = 'Elemento atualizada com sucesso.' if @elemento.update(elemento_params)
        if @elemento.errors.any?
          flash[:alert] = catch(@elemento)
          @params_for_reload = elemento_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = elemento_params
      end
      format.html { redirect_to edit_state_machine_diagram_elementos_path(@elemento, params: @params_for_reload, mqdiag_id: params[:mqelem][:mqdiag_id]) }
    end
  end

  def destroy
    respond_to do |format|
      begin
        flash[:notice] = 'Elemento removida com sucesso.' if @elemento.destroy
        flash[:alert] = catch(@elemento) if @elemento.errors.any?
      rescue StandardError => e
        flash[:error] = e.message
      end
      format.html { redirect_to edit_state_machine_diagram_diagramas_path(@elemento.mqdiag_id) }
    end
  end

  private
    def set_elemento
      @elemento = MQELEM.find(params[:id])
    end

    def set_diagrama
      @diagrama = MQDIAG.find(params[:mqdiag_id])
    end

    def elemento_params
      @params_for_reload = {}
      params.require(:mqelem).permit(:mqdiag_id, :descricao, :estereotipo)
    end
end

app/controllers/use_case_diagram/diagramas_controller.rb
class UseCaseDiagram::DiagramasController < ApplicationController
  before_action :set_diagrama, only: [:show, :edit, :update, :destroy]

  def index
    @diagramas = CSDIAG.where(user_id: current_user.id).order(id: :desc)
    @title = 'Lista de Diagramas de Caso de Uso'
  end

  def show
    flash[:notice] = "Diagrama gerado com sucesso."
    @title = 'Diagrama de Caso de Uso Gerado'
  end

  def new
    @diagrama = CSDIAG.new
    params_for_csasso
    @title = 'Novo Diagrama de Caso de Uso'
  end

  def edit
    @elementos = CSELEM.where(csdiag_id: @diagrama.id)
    params_for_csasso
    @title = 'Editando Diagrama de Caso de Uso'
  end

  def create
    respond_to do |format|
      begin
        @diagrama = CSDIAG.new(diagrama_params)
        if @diagrama.save
          flash[:notice] = 'Diagrama criado com sucesso.'
          format.html { redirect_to edit_use_case_diagram_diagramas_path(@diagrama) }
        end
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to new_use_case_diagram_diagramas_path(params: @params_for_reload) }
    end
  end

  def update
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama atualizado com sucesso.' if @diagrama.update(diagrama_params)
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to edit_use_case_diagram_diagramas_path(@diagrama, params: @params_for_reload) }
    end
  end

  def destroy
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama removido com sucesso.' if @diagrama.destroy
        flash[:alert] = catch(@diagrama) if @diagrama.errors.any?
      rescue StandardError => e
        flash[:error] = e.message
      end
      format.html { redirect_to use_case_diagram_diagramas_index_path }
    end
  end

  private
    def set_diagrama
      @diagrama = CSDIAG.find(params[:id])
    end

    def diagrama_params
      @params_for_reload = {}
      params.require(:csdiag).permit(:nome, csasso_attributes: [:id, :cselem_origem_id, :cselem_destino_id, :tipo_associacao, :estereotipo, :_destroy])
    end

    def params_for_csasso
      if @items = params[:csasso_attributes]
        @items.each do |i|
          @item = CSASSO.new(cselem_origem_id: @items[i]['cselem_origem_id'], cselem_destino_id: @items[i]['cselem_destino_id'], tipo_associacao: @items[i]['tipo_associacao'], estereotipo: @items[i]['estereotipo'])
          @diagrama.csasso.new(@item.attributes) if @items[i]['id'].blank?
        end
        return true
      end
      return false
    end
end

app/controllers/use_case_diagram/elementos_controller.rb
class UseCaseDiagram::ElementosController < ApplicationController
  before_action :set_elemento, only: [:edit, :update, :destroy]
  before_action :set_diagrama, only: [:new, :edit]

  def new
    @elemento = CSELEM.new
    @title = 'Novo Elemento'
  end

  def edit
    @title = 'Editando Elemento'
  end

  def create
    respond_to do |format|
      begin
        @elemento = CSELEM.new(elemento_params)
        if @elemento.save
          flash[:notice] = 'Elemento criada com sucesso.'
          format.html { redirect_to edit_use_case_diagram_elementos_path(@elemento, csdiag_id: params[:cselem][:csdiag_id]) }
        end
        if @elemento.errors.any?
          flash[:alert] = catch(@elemento)
          @params_for_reload = elemento_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = elemento_params
      end
      format.html { redirect_to new_use_case_diagram_elementos_path(params: @params_for_reload) }
    end
  end

  def update
    respond_to do |format|
      begin
        flash[:notice] = 'Elemento atualizada com sucesso.' if @elemento.update(elemento_params)
        if @elemento.errors.any?
          flash[:alert] = catch(@elemento)
          @params_for_reload = elemento_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = elemento_params
      end
      format.html { redirect_to edit_use_case_diagram_elementos_path(@elemento, params: @params_for_reload, csdiag_id: params[:cselem][:csdiag_id]) }
    end
  end

  def destroy
    respond_to do |format|
      begin
        flash[:notice] = 'Elemento removida com sucesso.' if @elemento.destroy
        flash[:alert] = catch(@elemento) if @elemento.errors.any?
      rescue StandardError => e
        flash[:error] = e.message
      end
      format.html { redirect_to edit_use_case_diagram_diagramas_path(@elemento.csdiag_id) }
    end
  end

  private
    def set_elemento
      @elemento = CSELEM.find(params[:id])
    end

    def set_diagrama
      @diagrama = CSDIAG.find(params[:csdiag_id])
    end

    def elemento_params
      @params_for_reload = {}
      params.require(:cselem).permit(:csdiag_id, :descricao, :estereotipo, :tipo_elemento)
    end
end

app/helpers/state_machine_diagram/elementos_helper.rb
module StateMachineDiagram::ElementosHelper
end

app/helpers/use_case_diagram/diagramas_helper.rb
module UseCaseDiagram::DiagramasHelper
end

app/helpers/use_case_diagram/elementos_helper.rb
module UseCaseDiagram::ElementosHelper
end

app/views/use_case_diagram/elementos/_form.html.erb
<h2 class="title">Novo Elemento para "<%= @diagrama.nome %>"</h2>
<%= form_for @elemento, url: url do |f| %>
  <%= f.text_field :csdiag_id, value: params[:csdiag_id], class: 'd-none' %>
  <div class="row">
    <div class="col-3">
      <div class="form-group">
        <%= f.label :descricao %>
        <%= f.text_field :descricao, value: val_of(@elemento, :descricao), class: 'form-control', autofocus: true %>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <%= f.label :estereotipo %>
        <%= f.text_field :estereotipo, value: val_of(@elemento, :estereotipo), class: 'form-control', autofocus: true %>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <%= f.label :tipo_elemento %>
        <%= f.select :tipo_elemento, CSELEM.tipo_elementos, {include_blank: false}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <button type="submit" class="btn btn-dark btn-block" style='margin-top: 35px;' accesskey="s">Efetivar Elem.</button>
      </div>
    </div>
    <div class="col-1">
      <div class="form-group">
        <button type="button" onclick="location.href='<%= edit_use_case_diagram_diagramas_path(params[:csdiag_id]) %>';" class="btn btn-dark btn-block" style="margin-top: 35px;" accesskey="v">Voltar</button>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-9">
      <div class="form-group">
        <button type="submit" class="btn btn-dark btn-block" style='margin-top: 35px;'>Efetivar Elemento</button>
      </div>
    </div>
    <div class="col-1">
      <div class="form-group">
        <button type="button" onclick="location.href='<%= edit_use_case_diagram_diagramas_path(params[:csdiag_id]) %>';" class="btn btn-dark btn-block" style="margin-top: 35px;">Voltar</button>
      </div>
    </div>
  </div>
<% end %>

app/views/use_case_diagram/elementos/edit.html.erb
<%= render 'form', url: use_case_diagram_elementos_path %>

app/views/use_case_diagram/elementos/new.html.erb
<%= render 'form', url: use_case_diagram_elementos_index_path %>