config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'tester_mode', to: 'application#set_tester_mode'
  devise_for :user, controllers: { registrations: 'users/registrations' }
  namespace :class_diagram do
    resources :diagramas
    resources :classes, except: [:index, :show]
  end
  namespace :use_case_diagram do
    resources :diagramas
    resources :elementos, except: [:index, :show]
  end
  namespace :state_machine_diagram do
    resources :diagramas
    resources :elementos, except: [:index, :show]
  end
  namespace :users do
    resource :resources, only: [:edit, :update]
  end
end

app/models/class_diagram/diagrama.rb
class ClassDiagram::Diagrama < ApplicationRecord
  belongs_to :user
  has_many :class_diagram_classe, class_name: 'ClassDiagram::Classe'
  validates :nome, presence: true
  before_validation :set_user
  before_destroy :remove_dependencias
  private
  def set_user
    self.user_id = Current.user.id
  end
  def remove_dependencias
    ClassDiagram::Classe.where(class_diagram_diagrama_id: id).delete_all
  end
end

app/controllers/class_diagram/diagramas_controller.rb
class ClassDiagram::DiagramasController < ApplicationController
  before_action :set_diagrama, only: [:show, :edit, :update, :destroy]

  def index
    @diagramas = CLDIAG.where(user_id: current_user.id).order(id: :desc)
    @title = 'Lista de Diagramas de Classes'
  end

  def show
    flash[:notice] = "Diagrama gerado com sucesso."
    @title = 'Diagrama de Classes Gerado'
  end

  def new
    @diagrama = CLDIAG.new
    params_for_clmeto
    @title = 'Novo Diagrama de Classes'
  end

  def edit
    @classes = CLCLAS.where(cldiag_id: @diagrama.id)
    params_for_clmeto
    @title = 'Editando Diagrama de Classes'
  end

  def create
    respond_to do |format|
      begin
        @diagrama = CLDIAG.new(diagrama_params)
        if @diagrama.save
          flash[:notice] = 'Diagrama criado com sucesso.'
          format.html { redirect_to edit_class_diagram_diagramas_path(@diagrama) }
        end
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to new_class_diagram_diagramas_path(params: @params_for_reload) }
    end
  end

  def update
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama atualizado com sucesso.' if @diagrama.update(diagrama_params)
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to edit_class_diagram_diagramas_path(@diagrama, params: @params_for_reload) }
    end
  end

  def destroy
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama removido com sucesso.' if @diagrama.destroy
        flash[:alert] = catch(@diagrama) if @diagrama.errors.any?
      rescue StandardError => e
        flash[:error] = e.message
      end
      format.html { redirect_to class_diagram_diagramas_index_path }
    end
  end

  private
    def set_diagrama
      @diagrama = CLDIAG.find(params[:id])
    end

    def diagrama_params
      @params_for_reload = {}
      params.require(:cldiag).permit(:nome, classo_attributes: [:id, :clclas_origem_id, :clclas_destino_id, :multi_origem, :multi_destino, :tipo_associacao, :estereotipo, :_destroy])
    end

    def params_for_clmeto
      if @items = params[:classo_attributes]
        @items.each do |i|
          @item = CLASSO.new(clclas_origem_id: @items[i]['clclas_origem_id'], clclas_destino_id: @items[i]['clclas_destino_id'], multi_origem: @items[i]['multi_origem'], multi_destino: @items[i]['multi_destino'], tipo_associacao: @items[i]['tipo_associacao'], estereotipo: @items[i]['estereotipo'])
          @diagrama.classo.new(@item.attributes) if @items[i]['id'].blank?
        end
        return true
      end
      return false
    end
end

app/controllers/state_machine_diagram/diagramas_controller.rb
class StateMachineDiagram::DiagramasController < ApplicationController
  before_action :set_diagrama, only: [:show, :edit, :update, :destroy]

  def index
    @diagramas = MQDIAG.where(user_id: current_user.id).order(id: :desc)
    @title = 'Lista de Diagramas de Máquina de Estado'
  end

  def show
    flash[:notice] = "Diagrama gerado com sucesso."
    @title = 'Diagrama de Máquina de Estado Gerado'
  end

  def new
    @diagrama = MQDIAG.new
    params_for_mqtran
    @title = 'Novo Diagrama de Máquina de Estado'
  end

  def edit
    @elementos = MQELEM.where(mqdiag_id: @diagrama.id)
    params_for_mqtran
    @title = 'Editando Diagrama de Máquina de Estado'
  end

  def create
    respond_to do |format|
      begin
        @diagrama = MQDIAG.new(diagrama_params)
        if @diagrama.save
          flash[:notice] = 'Diagrama criado com sucesso.'
          format.html { redirect_to edit_state_machine_diagram_diagramas_path(@diagrama) }
        end
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to new_state_machine_diagram_diagramas_path(params: @params_for_reload) }
    end
  end

  def update
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama atualizado com sucesso.' if @diagrama.update(diagrama_params)
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to edit_state_machine_diagram_diagramas_path(@diagrama, params: @params_for_reload) }
    end
  end

  def destroy
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama removido com sucesso.' if @diagrama.destroy
        flash[:alert] = catch(@diagrama) if @diagrama.errors.any?
      rescue StandardError => e
        flash[:error] = e.message
      end
      format.html { redirect_to state_machine_diagram_diagramas_index_path }
    end
  end

  private
    def set_diagrama
      @diagrama = MQDIAG.find(params[:id])
    end

    def diagrama_params
      @params_for_reload = {}
      params.require(:mqdiag).permit(:nome, :mqelem_inicial_id, :mqelem_final_id, mqtran_attributes: [:id, :mqelem_origem_id, :mqelem_destino_id, :descricao, :estereotipo, :_destroy])
    end

    def params_for_mqtran
      if @items = params[:mqtran_attributes]
        @items.each do |i|
          @item = MQTRAN.new(mqelem_origem_id: @items[i]['mqelem_origem_id'], mqelem_destino_id: @items[i]['mqelem_destino_id'], descricao: @items[i]['descricao'])
          @diagrama.mqtran.new(@item.attributes) if @items[i]['id'].blank?
        end
        return true
      end
      return false
    end
end

app/controllers/use_case_diagram/diagramas_controller.rb
class UseCaseDiagram::DiagramasController < ApplicationController
  before_action :set_diagrama, only: [:show, :edit, :update, :destroy]

  def index
    @diagramas = CSDIAG.where(user_id: current_user.id).order(id: :desc)
    @title = 'Lista de Diagramas de Caso de Uso'
  end

  def show
    flash[:notice] = "Diagrama gerado com sucesso."
    @title = 'Diagrama de Caso de Uso Gerado'
  end

  def new
    @diagrama = CSDIAG.new
    params_for_csasso
    @title = 'Novo Diagrama de Caso de Uso'
  end

  def edit
    @elementos = CSELEM.where(csdiag_id: @diagrama.id)
    params_for_csasso
    @title = 'Editando Diagrama de Caso de Uso'
  end

  def create
    respond_to do |format|
      begin
        @diagrama = CSDIAG.new(diagrama_params)
        if @diagrama.save
          flash[:notice] = 'Diagrama criado com sucesso.'
          format.html { redirect_to edit_use_case_diagram_diagramas_path(@diagrama) }
        end
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to new_use_case_diagram_diagramas_path(params: @params_for_reload) }
    end
  end

  def update
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama atualizado com sucesso.' if @diagrama.update(diagrama_params)
        if @diagrama.errors.any?
          flash[:alert] = catch(@diagrama)
          @params_for_reload = diagrama_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = diagrama_params
      end
      format.html { redirect_to edit_use_case_diagram_diagramas_path(@diagrama, params: @params_for_reload) }
    end
  end

  def destroy
    respond_to do |format|
      begin
        flash[:notice] = 'Diagrama removido com sucesso.' if @diagrama.destroy
        flash[:alert] = catch(@diagrama) if @diagrama.errors.any?
      rescue StandardError => e
        flash[:error] = e.message
      end
      format.html { redirect_to use_case_diagram_diagramas_index_path }
    end
  end

  private
    def set_diagrama
      @diagrama = CSDIAG.find(params[:id])
    end

    def diagrama_params
      @params_for_reload = {}
      params.require(:csdiag).permit(:nome, csasso_attributes: [:id, :cselem_origem_id, :cselem_destino_id, :tipo_associacao, :estereotipo, :_destroy])
    end

    def params_for_csasso
      if @items = params[:csasso_attributes]
        @items.each do |i|
          @item = CSASSO.new(cselem_origem_id: @items[i]['cselem_origem_id'], cselem_destino_id: @items[i]['cselem_destino_id'], tipo_associacao: @items[i]['tipo_associacao'], estereotipo: @items[i]['estereotipo'])
          @diagrama.csasso.new(@item.attributes) if @items[i]['id'].blank?
        end
        return true
      end
      return false
    end
end

app/controllers/use_case_diagram/elementos_controller.rb
class UseCaseDiagram::ElementosController < ApplicationController
  before_action :set_elemento, only: [:edit, :update, :destroy]
  before_action :set_diagrama, only: [:new, :edit]

  def new
    @elemento = CSELEM.new
    @title = 'Novo Elemento'
  end

  def edit
    @title = 'Editando Elemento'
  end

  def create
    respond_to do |format|
      begin
        @elemento = CSELEM.new(elemento_params)
        if @elemento.save
          flash[:notice] = 'Elemento criada com sucesso.'
          format.html { redirect_to edit_use_case_diagram_elementos_path(@elemento, csdiag_id: params[:cselem][:csdiag_id]) }
        end
        if @elemento.errors.any?
          flash[:alert] = catch(@elemento)
          @params_for_reload = elemento_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = elemento_params
      end
      format.html { redirect_to new_use_case_diagram_elementos_path(params: @params_for_reload) }
    end
  end

  def update
    respond_to do |format|
      begin
        flash[:notice] = 'Elemento atualizada com sucesso.' if @elemento.update(elemento_params)
        if @elemento.errors.any?
          flash[:alert] = catch(@elemento)
          @params_for_reload = elemento_params
        end
      rescue StandardError => e
        flash[:error] = e.message
        @params_for_reload = elemento_params
      end
      format.html { redirect_to edit_use_case_diagram_elementos_path(@elemento, params: @params_for_reload, csdiag_id: params[:cselem][:csdiag_id]) }
    end
  end

  def destroy
    respond_to do |format|
      begin
        flash[:notice] = 'Elemento removida com sucesso.' if @elemento.destroy
        flash[:alert] = catch(@elemento) if @elemento.errors.any?
      rescue StandardError => e
        flash[:error] = e.message
      end
      format.html { redirect_to edit_use_case_diagram_diagramas_path(@elemento.csdiag_id) }
    end
  end

  private
    def set_elemento
      @elemento = CSELEM.find(params[:id])
    end

    def set_diagrama
      @diagrama = CSDIAG.find(params[:csdiag_id])
    end

    def elemento_params
      @params_for_reload = {}
      params.require(:cselem).permit(:csdiag_id, :descricao, :estereotipo, :tipo_elemento)
    end
end

app/helpers/class_diagram/diagramas_helper.rb
module ClassDiagram::DiagramasHelper
end

app/helpers/state_machine_diagram/diagramas_helper.rb
module StateMachineDiagram::DiagramasHelper
end

app/helpers/use_case_diagram/diagramas_helper.rb
module UseCaseDiagram::DiagramasHelper
end

app/helpers/use_case_diagram/elementos_helper.rb
module UseCaseDiagram::ElementosHelper
end

app/views/use_case_diagram/diagramas/_csasso_fields.html.erb
<tr class="nested-fields">
  <td width="27.5%">
    <%= f.label :cselem_origem_id, 'Elem. Origem' %>
    <%= f.select :cselem_origem_id, CSELEM.where(csdiag_id: params[:id]).pluck(:descricao, :id), {include_blank: false}, {class: 'form-control ref-3'} %>
  </td>
  <td width="27.5%">
    <%= f.label :cselem_destino_id, 'Elem. Destino' %>
    <%= f.select :cselem_destino_id, CSELEM.where(csdiag_id: params[:id]).pluck(:descricao, :id), {include_blank: false}, {class: 'form-control'} %>
  </td>
  <td width="20%">
    <%= f.label :tipo_associacao, 'Associação' %>
    <%= f.select :tipo_associacao, CSASSO.associacoes, {include_blank: false}, {class: 'form-control'} %>
  </td>
  <td>
    <%= f.label :estereotipo, 'Esteótipo' %>
    <%= f.text_field :estereotipo, class: 'form-control', placeholder: 'Estereótipo' %>
  </td>
  <td width="5%"><br><%= link_to_remove_association f, class: 'btn btn-dark btn-block', style: 'margin-top: 10px;' do %>Excluir<% end %></td>
</tr>

app/views/use_case_diagram/diagramas/edit.html.erb
<h2 class="title">Editando Diagrama de Caso de Uso</h2>
<%= form_for @diagrama, url: use_case_diagram_diagramas_path do |f| %>
  <div class="row">
    <div class="col-4">
      <div class="form-group">
        <%= f.label :nome %>
        <%= f.text_field :nome, value: val_of(@diagrama, :nome), class: 'form-control', autofocus: true %>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <button type="submit" class="btn btn-dark btn-block" style='margin-top: 35px;' accesskey="s">Salvar Diagrama</button>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <%= link_to 'Gerar Diagrama', use_case_diagram_diagramas_path(params[:id]), class:"btn btn-dark btn-block", style: 'margin-top: 35px;', accesskey: 'g' %>
      </div>
    </div>
    <div class="col-1">
      <div class="form-group">
        <button type="button" onclick="location.href='<%= use_case_diagram_diagramas_index_path %>';" class="btn btn-dark btn-block" style="margin-top: 35px;", accesskey='v'>Voltar</button>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-9">
      <fieldset class="border p-2">
        <legend>Elementos</legend>
        <% if @elementos.empty? %><p class="alert-item">Nenhum elemento cadastrado.</p><% end %>
          <% if !@elementos.empty? %>
            <table>
              <thead>
                <tr>
                  <th>Descrição</th>
                  <th>Estereotipo</th>
                  <th>Tipo Elemento</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @elementos.each do |elemento| %>
                  <tr>
                    <td width="35%"><%= elemento.descricao %></td>
                    <td width="25%"><%= elemento.estereotipo %></td>
                    <td width="15%"><%= CSELEM.tipo_elementos.to_h.select{|key, value| value == elemento.tipo_elemento }.keys[0] %></td>
                    <td width="7.5%"><%= link_to 'Editar', edit_use_case_diagram_elementos_path(elemento, csdiag_id: params[:id]), class: 'btn btn-dark btn-block' %></td>
                    <td width="7.5%"><%= link_to 'Excluir', use_case_diagram_elementos_path(elemento), method: :delete, class: 'btn btn-dark btn-block' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
          <button type="button" onclick="location.href='<%= new_use_case_diagram_elementos_path(csdiag_id: params[:id]) %>';" class="btn btn-dark btn-block" accesskey="u">Novo Elemento</button>
      </fieldset>
    </div>
  </div>
  <div class="row">
    <div class="col-9">
      <fieldset class="border p-2">
        <legend>Lista de Associações</legend>
          <table>
          <thead class="<%= 'd-none' if f.object.csasso.empty? %>" id="thead-csasso">
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody class="csasso">
            <%= f.fields_for :csasso do |builder| %>
              <%= render 'csasso_fields', f: builder %>
            <% end %>
          </tbody>
        </table>
        <%= link_to_add_association f, :csasso, data: { thead: '#thead-csasso', focus: '.ref-3', association_insertion_node: '.csasso', association_insertion_method: :append }, class:'btn btn-dark btn-cocoon btn-block', accesskey: 'n' do %>Nova Associação<% end %>
      </fieldset>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <button type="submit" class="btn btn-dark btn-block" style='margin-top: 35px;'>Salvar Diagrama</button>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <%= link_to 'Gerar Diagrama', use_case_diagram_diagramas_path(params[:id]), class:"btn btn-dark btn-block", style: 'margin-top: 35px;' %>
      </div>
    </div>
    <div class="col-1">
      <div class="form-group">
        <button type="button" onclick="location.href='<%= use_case_diagram_diagramas_index_path %>';" class="btn btn-dark btn-block" style="margin-top: 35px;">Voltar</button>
      </div>
    </div>
  </div>
<% end %>

app/views/use_case_diagram/diagramas/index.html.erb
<h2 class="title">Meus Diagramas de Caso de Uso</h2>
<div class="row">
  <div class="col-6">
    <button type="button" onclick="location.href='<%= new_use_case_diagram_diagramas_path %>';" class="btn btn-dark btn-block" accesskey="r">Novo Diagrama</button>
  </div>
</div>

<div class="row">
  <div class="col-6">
    <fieldset class="border p-2">
      <legend>Diagramas</legend>
      <% if @diagramas.empty? %><p class="alert-item">Nenhum diagrama cadastrado.</p><% end %>
      <% if !@diagramas.empty? %>
        <% @diagramas.each do |diagrama| %>
          <table>
            <tbody>
              <tr>
                <td width="70%"><%= diagrama.nome %></td>
                <td width="15%"><%= link_to 'Editar', edit_use_case_diagram_diagramas_path(diagrama), class: 'btn btn-dark btn-block' %></td>
                <td width="15%"><%= link_to 'Gerar', use_case_diagram_diagramas_path(diagrama), class: 'btn btn-dark btn-block' %></td>
                <td width="15%"><%= link_to 'Excluir', use_case_diagram_diagramas_path(diagrama), method: :delete, class: 'btn btn-dark btn-block' %></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/use_case_diagram/diagramas/new.html.erb
<h2 class="title">Criando Diagrama de Caso de Uso</h2>
<%= form_for @diagrama, url: use_case_diagram_diagramas_index_path do |f| %>
  <div class="row">
    <div class="col-4">
      <div class="form-group">
        <%= f.label :nome %>
        <%= f.text_field :nome, value: val_of(@diagrama, :nome), class: 'form-control', autofocus: true %>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <button type="submit" class="btn btn-dark btn-block" style='margin-top: 35px;' accesskey="s">Criar Diagrama</button>
      </div>
    </div>
    <div class="col-1">
      <div class="form-group">
        <button type="button" onclick="location.href='<%= use_case_diagram_diagramas_index_path %>';" class="btn btn-dark btn-block" style="margin-top: 35px;" accesskey="v">Voltar</button>
      </div>
    </div>
  </div>
<% end %>